// Code generated by protoc-gen-go. DO NOT EDIT.
// source: baap_transaction.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e5be2d88b328fd, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// for TX execution or query
type Invocation struct {
	Fcn                  string            `protobuf:"bytes,1,opt,name=fcn,proto3" json:"fcn,omitempty"`
	Args                 [][]byte          `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Meta                 map[string][]byte `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Invocation) Reset()         { *m = Invocation{} }
func (m *Invocation) String() string { return proto.CompactTextString(m) }
func (*Invocation) ProtoMessage()    {}
func (*Invocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e5be2d88b328fd, []int{1}
}

func (m *Invocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invocation.Unmarshal(m, b)
}
func (m *Invocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invocation.Marshal(b, m, deterministic)
}
func (m *Invocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invocation.Merge(m, src)
}
func (m *Invocation) XXX_Size() int {
	return xxx_messageInfo_Invocation.Size(m)
}
func (m *Invocation) XXX_DiscardUnknown() {
	xxx_messageInfo_Invocation.DiscardUnknown(m)
}

var xxx_messageInfo_Invocation proto.InternalMessageInfo

func (m *Invocation) GetFcn() string {
	if m != nil {
		return m.Fcn
	}
	return ""
}

func (m *Invocation) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Invocation) GetMeta() map[string][]byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

//for deployment or removal
type Deployment struct {
	Owner                string      `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string      `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Payload              *Invocation `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8e5be2d88b328fd, []int{2}
}

func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (m *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(m, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Deployment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Deployment) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Deployment) GetPayload() *Invocation {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "protos.Transaction")
	proto.RegisterType((*Invocation)(nil), "protos.Invocation")
	proto.RegisterMapType((map[string][]byte)(nil), "protos.Invocation.MetaEntry")
	proto.RegisterType((*Deployment)(nil), "protos.Deployment")
}

func init() { proto.RegisterFile("baap_transaction.proto", fileDescriptor_a8e5be2d88b328fd) }

var fileDescriptor_a8e5be2d88b328fd = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x65, 0x2f, 0xf1, 0x23, 0x93, 0x13, 0x64, 0x11, 0x59, 0xc4, 0x22, 0xa4, 0x4a, 0x21, 0x41,
	0xce, 0x42, 0xd1, 0x4e, 0xb4, 0xb0, 0xb0, 0x59, 0xac, 0x6c, 0x64, 0x2e, 0x8e, 0x72, 0x5c, 0xb2,
	0x1b, 0x36, 0x6b, 0x64, 0x1b, 0xff, 0x89, 0xff, 0x55, 0x76, 0x93, 0x5c, 0x0a, 0xab, 0x79, 0x6f,
	0x76, 0xde, 0xcc, 0xdb, 0x07, 0xa7, 0x6b, 0xc4, 0xf6, 0xcd, 0x1a, 0x54, 0x1d, 0x56, 0x76, 0xa3,
	0x55, 0xd9, 0x1a, 0x6d, 0x35, 0xdf, 0x0f, 0xa5, 0xcb, 0xef, 0x20, 0x7d, 0x99, 0x1f, 0x39, 0x87,
	0xd8, 0xba, 0x96, 0x04, 0xcb, 0x58, 0x71, 0x24, 0x03, 0xe6, 0x02, 0x0e, 0x5a, 0x74, 0xb5, 0xc6,
	0x77, 0xb1, 0xc8, 0x58, 0xb1, 0x94, 0x13, 0xcd, 0x7f, 0x19, 0xc0, 0x93, 0xea, 0x75, 0x85, 0x41,
	0x7c, 0x0c, 0xd1, 0x47, 0xa5, 0x82, 0x36, 0x91, 0x1e, 0xfa, 0x75, 0x68, 0x3e, 0x3b, 0xb1, 0xc8,
	0xa2, 0x62, 0x29, 0x03, 0xe6, 0x97, 0x10, 0x37, 0x64, 0x51, 0x44, 0x59, 0x54, 0xa4, 0xab, 0xf3,
	0xc1, 0x4f, 0x57, 0xce, 0x7b, 0xca, 0x67, 0xb2, 0xf8, 0xa8, 0xac, 0x71, 0x32, 0x4c, 0x9e, 0x5d,
	0x43, 0xb2, 0x6b, 0xf9, 0x23, 0x5b, 0x72, 0xd3, 0x91, 0x2d, 0x39, 0x7e, 0x02, 0x7b, 0x3d, 0xd6,
	0x5f, 0x34, 0xba, 0x1b, 0xc8, 0xed, 0xe2, 0x86, 0xe5, 0x3f, 0x00, 0x0f, 0xd4, 0xd6, 0xda, 0x35,
	0xa4, 0xac, 0x9f, 0xd3, 0xdf, 0x8a, 0xcc, 0xa8, 0x1d, 0x88, 0xb7, 0xa8, 0xb0, 0x19, 0xc4, 0x89,
	0x0c, 0xd8, 0xff, 0xb8, 0x27, 0xd3, 0x6d, 0xb4, 0x12, 0x51, 0x68, 0x4f, 0x94, 0x5f, 0xcc, 0x59,
	0xc4, 0x19, 0x2b, 0xd2, 0x15, 0xff, 0xef, 0x7f, 0x97, 0xcf, 0xfd, 0xe1, 0xeb, 0x18, 0xf3, 0x7a,
	0xa8, 0x57, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x35, 0xde, 0x04, 0x41, 0x8f, 0x01, 0x00, 0x00,
}
